# Site settings
title: Gotham web framework
email: git@msrd0.de
description: >-
  A flexible web framework that promotes stability, safety, security and speed.
baseurl: ""
url: "https://gotham.rs"
github_username:  gotham-rs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
